accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views


app_name = 'accounts'


urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/accounts/login'), name='logout'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^stats$', views.StatsView.as_view(), name='stats'),
    url(r'^order/(?P<pk>[0-9]+)/$', views.OrderView.as_view(), name='order'),
    url(r'^order/check/$', views.CheckOrderView.as_view(), name='check_order'),
    url(r'^order/add/$', views.add_order, name='add_order'),
    url(r'^set_order_status/$', views.set_order_status, name='set_order_status'),
]

cafe/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from . import views


app_name = 'cafe'


urlpatterns = [
    url(r'^$', views.MostPopularView.as_view(), name='most_popular'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^cart/$', login_required(TemplateView.as_view(template_name='cafe/cart.html')), name='cart'),
    url(r'^cart/render/$', views.RenderCartView.as_view(), name='render_cart')
]

motmom_cafe/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('cafe.urls')),
    url(r'^accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum, F
from django.shortcuts import get_object_or_404
from django.utils.timezone import now
from base64 import b64encode, b64decode

from cafe.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField('Дата', auto_now_add=True)
    completed = models.BooleanField('Выполнено', default=False)

    @property
    def sum(self):
        return sum([item.product.price * item.count for item in self.orderitem_set.all()])
        # return self.orderitem_set.aggregate(sum=Sum(F('product.price') * F('count')))

    @property
    def token(self):
        token = '%s#%s' % (self.date, self.pk)
        return b64encode(bytes(token, 'utf-8')).decode()

    @staticmethod
    def from_token(token):
        date, pk = b64decode(bytes(token, 'utf-8')).decode().split('#')
        return get_object_or_404(Order, pk=pk, date=date)

    def __str__(self):
        date_str = self.date.astimezone().strftime('%d/%m/%y %H:%M:%S')
        return '%s, %s, %s, %s' % (self.user, date_str, self.sum, self.completed)

    class Meta:
        db_table = 'order'
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    count = models.PositiveIntegerField('Количество', default=1)

    def __str__(self):
        return '%s, %s, %s' % (self.order.pk, self.product, self.count)

    class Meta:
        db_table = 'order_item'
        verbose_name = 'Элемент заказа'
        verbose_name_plural = 'Элементы заказа'

accounts/views.py
import json
from itertools import groupby

from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.views.generic import DetailView, ListView, RedirectView

from cafe.models import Product
from .models import Order, OrderItem


class ProfileView(LoginRequiredMixin, ListView):
    template_name = 'accounts/profile.html'
    model = Order
    context_object_name = 'orders'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        context['sum'] = sum(o.sum for o in self.get_queryset() if o.completed)
        return context


class StatsView(UserPassesTestMixin, DetailView):
    template_name = 'accounts/stats.html'
    context_object_name = 'stat_items'

    def test_func(self):
        return self.request.user.is_superuser

    def get_queryset(self):
        year = self.request.GET['year']
        month = self.request.GET['month']
        return Order.objects.filter(completed=True, date__year=year, date__month=month)

    def get_object(self, queryset=None):
        groups = groupby(self.get_queryset(), lambda o: o.user)
        return [{'user': user, 'sum': sum(o.sum for o in orders)} for user, orders in groups]

    def get_context_data(self, **kwargs):
        context = super(StatsView, self).get_context_data(**kwargs)
        context['year'] = self.request.GET['year']
        context['month'] = self.request.GET['month']
        return context


@require_POST
@login_required
def add_order(request):
    cart = json.loads(request.POST['cart'])
    order = Order(user=request.user)
    order.save()

    for pk, count in cart.items():
        if count > 0:
            item = OrderItem(order=order, product=Product.objects.get(pk=pk), count=count)
            item.save()

            order.orderitem_set.add(item)

    order.save()
    return JsonResponse({'status': 'success'})


class OrderView(LoginRequiredMixin, DetailView):
    template_name = 'accounts/order.html'
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderView, self).get_context_data(**kwargs)
        context['order_items'] = list(self.get_object().orderitem_set.all())
        return context


class CheckOrderView(RedirectView):
    http_method_names = ['post']

    def get_redirect_url(self, *args, **kwargs):
        request = self.request
        token = request.POST.get('token')
        order = Order.from_token(token)

        if request.user == order.user or request.user.is_superuser:
            return reverse('accounts:order', args=(order.pk,))
        else:
            return reverse('cafe:most_popular')


@require_POST
@user_passes_test(lambda u: u.is_superuser)
def set_order_status(request):
    order = Order.objects.get(pk=request.POST['pk'])
    order.completed = request.POST['status']
    order.save()
    return JsonResponse({'status': 'success'})

templates/accounts/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Вход в аккаунт {% endblock title %}
{% block styles %}<link rel="stylesheet" href="{% static 'css/login.css' %}">{% endblock %}
{% block content %}
<form action="" method="POST" class="col-md-offset-5 login" style="display: inline-grid; margin-top: 15%;">
    {% csrf_token %}
    <table>
        <tr>
            <td><h3>Вход в аккаунт</h3></td>
        </tr>
        <tr>
            <td><label for="username">Имя пользователя:</label></td>
        </tr>
        <tr>
            <td><input type="text" id="username" name="username"></td>            
        </tr>
        <tr>
            <td><label for="password">Пароль:</label></td>
        </tr>
        <tr>
            <td><input type="password" id="password" name="password"></td>            
        </tr>
        <tr>
            <td><input type="submit" value="Войти"></td>
        </tr>
    </table>
</form>
{% endblock content %}

templates/accounts/order.html
{% extends 'header.html' %}
{% load staticfiles %}
{% block title %} Заказ {% endblock title %}
{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/order.css' %}">
{% endblock %}

{% block main_content %}
    <div class="col-md-offset-4 col-md-3">
        <div class="row">
            {% for item in order_items %}
                <div class="col-md-12">
                    <div class="row my-row">
                        <div class="col-md-offset-4 col-md-2">
                            {% include 'cafe/product_detail.html' with product=item.product %}
                        </div>
                        <div class="col-md-offset-2 col-md-1" style="margin-top: 50px;">{{ item.count }}</div>
                    </div>
                </div>
            {% endfor %}
        </div>

        {% if user.is_superuser %}
        <div class="row" style="margin-top: 50px;">
            <button class="col-md-offset-2 col-md-4" onclick="setOrderStatus({{ order.pk }}, true)">Подтвердить оплату</button>
            <button class="col-md-offset-1 col-md-4" onclick="setOrderStatus({{ order.pk }}, false)">Отменить заказ</button>
        </div>
        {% endif %}
    </div>
{% endblock main_content %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/order.js' %}"></script>
{% endblock %}

templates/accounts/profile.html
{% extends 'header.html' %}
{% load staticfiles %}
{% load qr_tags %}
{% block title %} Профиль {% endblock title %}
{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block main_content %}

    <div class="col-md-offset-4 col-md-4">
        <div style="margin-bottom: 5%; font-style: italic; font-weight: bold;">В этом месяце ({% now 'F' %}) вы уже потратили {{ sum }} рублей.</div>

        <div>
            {% for order in orders %}
                <div class="row my-row">
                    <div class="col-md-1 item">
                        <div class="round completed-{{ order.completed }}"></div>
                    </div>
                    <div class="col-md-3">{% qr_from_text order.token 's' %}</div>
                    <div class="col-md-4 item"><a href="{% url 'accounts:order' pk=order.pk %}">{{ order.date }}</a></div>
                    <div class="col-md-3 item">{{ order.sum }} рублей</div>
                    <img class="col-md-1 item" src="https://clipboardjs.com/assets/images/clippy.svg" style="cursor: pointer;" onclick="copyTextToClipboard('{{ order.token }}')">
                </div>
            {% endfor %}
        </div>

        {% if user.is_superuser %}
            <div style="margin-top: 3%;">
                <div style="margin-bottom: 10px;">Административные возможности</div>

                <div>
                    <form action="{% url 'accounts:check_order' %}" method="post" style="display: inline-block;">
                        {% csrf_token %}
                        <input placeholder="код заказа" type="text" autocomplete="off" name="token">
                        <input type="submit" class="btn btn-default" value="Получить заказ">
                    </form>
                    <a href="{% url 'accounts:stats' %}?year={% now 'Y' %}&month={% now 'n' %}" class="btn btn-default" style="margin-left: 100px;">Статистика</a>
                    <a href="{% url 'admin:index' %}" class="btn btn-default">Админка</a>
                </div>
            </div>
        {% endif %}

    </div>

{% endblock main_content %}

templates/accounts/stats.html
{% extends 'header.html' %}
{% load staticfiles %}
{% block title %} Статистика {% endblock title %}
{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/stats.css' %}">
{% endblock %}

{% block main_content %}
    <div class="col-md-offset-4 col-md-3">
        <div class="row">
            <form class="col-md-offset-1 col-md-10" action="{% url 'accounts:stats' %}" method="get">
                <div class="row">
                    <input class="col-md-3" type="number" min="2000" max="2099" autocomplete="off" name="year" value="{{ year }}">
                    <input class="col-md-offset-1 col-md-3"  type="number" min="1" max="31" autocomplete="off" name="month" value="{{ month }}">
                    <input class="col-md-offset-1 col-md-4"  type="submit" value="Показать">
                </div>
            </form>
        </div>

        <div class="row" style="margin-top: 30px;">
            <div class="col-md-offset-1 col-md-10">
                <div class="row my-row">
                    <div class="col-md-offset-1 col-md-5">Пользователь</div>
                    <div class="col-md-offset-1 col-md-5">Сумма</div>
                </div>

                {% for item in stat_items %}
                    <div class="row my-row">
                        <div class="col-md-offset-1 col-md-5">{{ item.user.username }}</div>
                        <div class="col-md-offset-1 col-md-5">{{ item.sum }}</div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock main_content %}