cafe/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from . import views


app_name = 'cafe'


urlpatterns = [
    url(r'^$', views.MostPopularView.as_view(), name='most_popular'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^cart/$', login_required(TemplateView.as_view(template_name='cafe/cart.html')), name='cart'),
    url(r'^cart/render/$', views.RenderCartView.as_view(), name='render_cart')
]

motmom_cafe/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('cafe.urls')),
    url(r'^accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cafe/models.py
# coding: utf-8

from __future__ import unicode_literals

from django.db import models


class Category(models.Model):
    name = models.CharField('Название', max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'category'
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField('Название', max_length=20)
    preview = models.ImageField('Изображение', upload_to='products')
    price = models.PositiveIntegerField('Цена', default=0)
    purchases_count = models.PositiveIntegerField('Количество покупок', default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

cafe/views.py
# coding: utf-8

import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, ListView

from .models import Category, Product


class MenuView(LoginRequiredMixin, DetailView):
    template_name = 'cafe/menu.html'
    model = Category
    context_object_name = 'checked_category'

    categories = Category.objects.all()
    MOST_POPULAR_CATEGORY = Category(id='', name='Самое популярное')

    def get_object(self, queryset=None):
        return self.MOST_POPULAR_CATEGORY

    def get_context_data(self, **kwargs):
        context = super(MenuView, self).get_context_data(**kwargs)
        context['categories'] = [self.MOST_POPULAR_CATEGORY] + list(self.categories)
        return context


class MostPopularView(MenuView):
    def get_context_data(self, **kwargs):
        context = super(MostPopularView, self).get_context_data(**kwargs)
        context['products'] = Product.objects.order_by('-purchases_count')[:5]
        return context


class CategoryView(MenuView):
    def get_object(self, queryset=None):
        return next(cat for cat in self.categories if cat.id == int(self.kwargs['pk']))

    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        context['products'] = self.get_object().product_set.all()
        return context


class RenderCartView(LoginRequiredMixin, ListView):
    template_name = 'cafe/cart.html'
    http_method_names = ['post']
    context_object_name = 'products'
    model = Product

    def get_queryset(self):
        products = json.loads(self.request.POST['products'])
        return Product.objects.filter(pk__in=products)

    def post(self, request):
        return self.get(request)

templates/cafe/cart.html
{% extends 'header.html' %}
{% load staticfiles %}
{% block title %} Корзина {% endblock title %}
{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
{% endblock %}
{% block main_content %}
    {% if products %}
        <div class="col-md-offset-3 col-md-6">
            {% for product in products %}
                <div class="row my-row" style="margin-top: 20px;">
                    <div class="col-md-offset-3 col-md-2">
                        {% include 'cafe/product_detail.html' %}
                    </div>
                    <input class="product col-md-2" style="margin-top: 30px;" type="number" value="0" min="0" autocomplete="off" id="{{ product.id }}">
                    <div class="remove-product col-md-2" style="margin-top: 30px; cursor: pointer;">&times;</div>
                </div>
            {% endfor %}
            <input id="add-order" type="submit" value="Заказать" style="margin-top: 50px; margin-left: 350px;">
        </div>
    {% else %}
        <h4 class="col-md-offset-5 col-md-2" style="margin-top: 10%; color: red;">В корзине пусто</h4>
    {% endif %}
{% endblock main_content %}
{% block scripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
{% endblock %}

templates/cafe/menu.html
{% extends 'header.html' %}
{% load staticfiles %}
{% block title %} Меню {% endblock title %}
{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
{% endblock %}
{% block main_content %}
<div class="col-md-offset-1 col-md-1" style="margin-top: 5%;">
    {% for category in categories %}
        <a class="{% if category.id == checked_category.id %}active{% endif %}" style="display: block;"
           href="{% if category.id == '' %}{% url 'cafe:most_popular' %}{% else %}{% url 'cafe:category' pk=category.id %}{% endif %}"
        >
            {{ category.name }}
        </a>
    {% endfor %}
</div>
<div class="col-md-offset-1 col-md-6">
    <div class="row">
        <h4 class="col-md-offset-5" style="color: red;">{{ checked_category.name }}</h4>
    </div>
    <div class="row" style="margin-right: 5%; margin-bottom: 5%; height: 700px;">
    {% for product in products %}
        <div class="col-md-offset-1 col-md-3" style="border: 1px solid black; margin-top: 20px; padding: 10px;">
            {% include 'cafe/product_detail.html' %}
            <input class="product" type="number" value="0" min="0" autocomplete="off" id="{{ product.id }}">
        </div>
    {% endfor %}
    </div>
</div>
{% endblock main_content %}
{% block scripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/menu.js' %}"></script>
{% endblock %}

templates/cafe/product_detail.html
<img src="{{ product.preview.url }}">
<div>{{ product.name }}</div>