accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views


app_name = 'accounts'


urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/accounts/login'), name='logout'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^stats$', views.StatsView.as_view(), name='stats'),
    url(r'^order/(?P<pk>[0-9]+)/$', views.OrderView.as_view(), name='order'),
    url(r'^order/check/$', views.CheckOrderView.as_view(), name='check_order'),
    url(r'^order/add/$', views.add_order, name='add_order'),
    url(r'^set_order_status/$', views.set_order_status, name='set_order_status'),
]

cafe/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from . import views


app_name = 'cafe'


urlpatterns = [
    url(r'^$', views.MostPopularView.as_view(), name='most_popular'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^cart/$', login_required(TemplateView.as_view(template_name='cafe/cart.html')), name='cart'),
    url(r'^cart/render/$', views.RenderCartView.as_view(), name='render_cart')
]

motmom_cafe/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('cafe.urls')),
    url(r'^accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/png">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.0.0/bootstrap-social.min.css"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        {% block styles %}{% endblock %}
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                  <nav class="navbar navbar-default navbar-fixed-bottom row" role="navigation">
                    <div class="col-md-offset-1 col-md-2" style="margin-top: 15px;">
                      &copy; Панов Илья, 2017 г.
                    </div>
                    <div class="col-md-offset-6 col-md-2" style="margin-top: 10px; max-width: 210px;">
                      <a href="https://github.com/i-panov/motmom_cafe" target="_blank" class="btn btn-block btn-social btn-github">
                        <span class="fa fa-github"></span> Sign in with GitHub
                      </a>
                    </div>
                  </nav>
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
        {% block scripts %}{% endblock %}
    </body>
</html>

templates/header.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block styles %}<link rel="stylesheet" href="{% static 'css/header.css' %}">{% endblock %}
{% block content %}
<div class="row" style="margin-top: 2%;">
    <div class="col-md-2" style="padding-left: 10%;">Кафе MOTMOM</div>
    <div class="col-md-offset-3 col-md-4">
        <a href="{% url 'cafe:most_popular' %}" class="btn btn-default">Главная</a>
        <a href="{% url 'cafe:cart' %}" id="cart" class="btn btn-default">Корзина</a>
    </div>
    <div class="col-md-offset-1 col-md-2" style="padding-left: 8%;">
        <div style="display: inline-block;"><a href="{% url 'accounts:profile' %}">{{ user.username }}</a></div>
        <a href="{% url 'accounts:logout' %}" class="btn btn-default">Выйти</a>
    </div>
</div>
<div class="row" style="margin-top: 2%;">
{% block main_content %}{% endblock main_content %}
</div>
{% endblock content %}
{% block scripts %}<script type="text/javascript" src="{% static 'js/header.js' %}"></script>{% endblock %}